[build-system]
requires = ["setuptools", "wheel", "scikit-build @ https://github.com/scikit-build/scikit-build/archive/14120db1a2ae0c1661a1b5a284f57b51b55ec066.zip", "cmake", "ninja"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp*"
archs = "all"
build-verbosity = 1
